### ISSUE TITLE
Drop Down menu for "NMR Data Type" only shows one option properly

### ISSUE THREAD

**Issue by chanana** [liningtonlab/madbyte#9]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/15051933/112166090-b667b480-8bc5-11eb-9615-a6293049ac0f.png">

OR 

<img width="499" alt="image" src="https://user-images.githubusercontent.com/15051933/112166132-bebfef80-8bc5-11eb-9143-3fcbfd603663.png">

Similar things happen for other drop down menus as well:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/15051933/112166433-00509a80-8bc6-11eb-9810-4405f91c64b5.png">

**Comment by Jmegan042** [comment]
Hi Shaurya, 

This problem seems to be tied to the way PyQT5 interacts with MacOS in the styling. It may be possible to solve this issue by forcing the styling into "windows" mode (which will change the look of a few things from the familiar mac look). 

To do this, in the madbyte_gui.py file under line 652 add: 
`app.setStyle('Windows')`

Let me know if that fixes it, and if so, we will add it to the next version. 

Thanks!

**Comment by chanana** [comment]
Awesome, that worked!

<img width="409" alt="image" src="https://user-images.githubusercontent.com/15051933/112178636-4dd20500-8bd0-11eb-92da-982061e6140f.png">
